name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Install dependencies
        run: dotnet restore Tambola.sln

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Run Unit Tests with Coverage
        run: dotnet test Tambola.sln --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Convert Coverage Report to Cobertura
        run: reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:TestResults/CoverageReport

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          dotnet sonarscanner begin /k:"SalikeHassan_Tambola" /o:"$SONAR_ORG" /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.vscoveragexml.reportsPaths=TestResults/**/coverage.cobertura.xml
          
          dotnet build Tambola.sln --configuration Release
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
