name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Install dependencies
        run: dotnet restore Tambola.sln

      - name: Build the project
        run: dotnet build Tambola.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test Tambola.sln --logger trx --results-directory TestResults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          dotnet sonarscanner begin /k:"SalikeHassan_Tambola" /o:"$SONAR_ORG" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths=TestResults/coverage.cobertura.xml
          dotnet build Tambola.sln --configuration Release
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
